apiVersion: apps/v1

kind: Deployment


metadata:

  name: employee-api

<<<<<<< HEAD
  namespace: employee-dev
=======
  namespace: employee-prod
>>>>>>> 74950808049ba5fe4b83f659248308a2a9fea6e7



spec:

  replicas: 3


  selector:

    matchLabels:

      app: employee-api



  template:


    metadata:

      labels:

        app: employee-api



    spec:


      containers:


      - name: employee-api


<<<<<<< HEAD
        image: 786228585523.dkr.ecr.ap-southeast-1.amazonaws.com/employee-management-api:latest
        imagePullPolicy: Always
=======
        image: your-dockerhub-user/employee-api:v1

>>>>>>> 74950808049ba5fe4b83f659248308a2a9fea6e7

        ports:

        - containerPort: 8080



        env:


        - name: SPRING_DATASOURCE_URL

          value: jdbc:mysql://mysql-service:3306/employee_db



        - name: SPRING_DATASOURCE_USERNAME

          valueFrom:

            secretKeyRef:

              name: employee-secret

              key: DB_USERNAME



        - name: SPRING_DATASOURCE_PASSWORD

          valueFrom:

            secretKeyRef:

              name: employee-secret

              key: DB_PASSWORD