apiVersion: apps/v1

kind: Deployment


metadata:

  name: employee-api

  namespace: employee-prod



spec:

  replicas: 3


  selector:

    matchLabels:

      app: employee-api



  template:


    metadata:

      labels:

        app: employee-api



    spec:


      containers:


      - name: employee-api


        image: your-dockerhub-user/employee-api:v1


        ports:

        - containerPort: 8080



        env:


        - name: SPRING_DATASOURCE_URL

          value: jdbc:mysql://mysql-service:3306/employee_db



        - name: SPRING_DATASOURCE_USERNAME

          valueFrom:

            secretKeyRef:

              name: employee-secret

              key: DB_USERNAME



        - name: SPRING_DATASOURCE_PASSWORD

          valueFrom:

            secretKeyRef:

              name: employee-secret

              key: DB_PASSWORD